version: '3.8'

services:
  postgres:
    image: postgres
    container_name: ConfigDBContainer
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: ConfigDB
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ThisNewConfig
    volumes:
      - postgres_data:/var/lib/postgresql/data

  spring-boot-app:
    build:
      context: /Backend
      dockerfile: Dockerfile
    container_name: ConfigManager
    ports:
      - "8081:8080"
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/ConfigDB
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: ThisNewConfig

volumes:
  postgres_data:
